<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NDATSTNPC074" name="com.markit.kyc.citrus.BatchUploadTest" tests="1" failures="1" timestamp="18 May 2016 05:42:15 GMT" time="47.469" errors="0">
  <testcase name="batchUploadTest" time="47.469" classname="com.markit.kyc.citrus.BatchUploadTest">
    <failure type="com.consol.citrus.exceptions.TestCaseFailedException" message="Test case failed">
      <![CDATA[com.consol.citrus.exceptions.TestCaseFailedException: Test case failed
	at com.consol.citrus.TestCase.doExecute(TestCase.java:91)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.testng.AbstractTestRunner.run(AbstractTestRunner.java:40)
	at com.consol.citrus.testng.AbstractTestNGCitrusTest.run(AbstractTestNGCitrusTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: com.consol.citrus.exceptions.ValidationException: Validation failed for column: 'ENTITY_SNAP_COUNT' found value: '3' expected value: 1
	at com.consol.citrus.actions.ExecuteSQLQueryAction.validateSingleValue(ExecuteSQLQueryAction.java:296)
	at com.consol.citrus.actions.ExecuteSQLQueryAction.performControlResultSetValidation(ExecuteSQLQueryAction.java:242)
	at com.consol.citrus.actions.ExecuteSQLQueryAction.performValidation(ExecuteSQLQueryAction.java:214)
	at com.consol.citrus.actions.ExecuteSQLQueryAction.doExecute(ExecuteSQLQueryAction.java:96)
	at com.consol.citrus.actions.AbstractDatabaseConnectingTestAction.execute(AbstractDatabaseConnectingTestAction.java:67)
	at com.consol.citrus.container.Template.doExecute(Template.java:105)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.TestCase.run(TestCase.java:190)
	at com.consol.citrus.TestCase.doExecute(TestCase.java:86)
	... 27 more
]]>
    </failure>
  </testcase> <!-- batchUploadTest -->
</testsuite> <!-- com.markit.kyc.citrus.BatchUploadTest -->
